[build.environment]
  NODE_VERSION='9.4.0'
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_PROD_ETHEREUM_PROVIDER="https://kovan.infura.io/v3/9c26dd38fd2e44e6bcff6a133eb67930"
  REACT_APP_PROD_ARBITRABLE_TOKEN_LIST_ADDRESS="0x380de0301572d977ed091d42d99164eb91c82500"
  REACT_APP_PROD_PATCH_TOKEN_URL="https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/token"

[context.production.environment]
  REACT_APP_PROD_ETHEREUM_PROVIDER="https://mainnet.infura.io/v3/9c26dd38fd2e44e6bcff6a133eb67930"
  REACT_APP_PROD_ARBITRABLE_TOKEN_LIST_ADDRESS=""
  REACT_APP_PROD_PATCH_TOKEN_URL=""
